kind: pipeline
name: default

steps:
  - name: build_zfs_2
    image: akhenakh/zfs-arch
    commands:
      - pacman -Sy --noconfirm --needed go gcc
      - go test -v 
    when:
      branch:
        - main
      event:
        - push

  - name: build_zfs_08
    image: ubuntu:focal
    commands:
      - apt-get update
      - apt-get install -y kmod zfsutils-linux libzfslinux-dev software-properties-common 
      - add-apt-repository ppa:longsleep/golang-backports
      - apt-get update
      - apt-get install -y  golang-go
      - go test -v
    when:
      branch:
        - zfs-08
      event:
        - push