kind: pipeline
name: default

steps:
  - name: build_zfs2
    image: archlinux
    commands:
      - pacman -Sy --noconfirm --needed git base-devel
      - git clone https://aur.archlinux.org/yay.git
      - cd yay
      - makepkg -si
      - yay -y zfs-linux

  - name: build_zfs_08
    image: ubuntu:focal
    commands:
      - apt-get update
      - apt-get install -y kmod zfsutils-linux libzfslinux-dev software-properties-common 
      - add-apt-repository ppa:longsleep/golang-backports
      - apt-get update
      - apt-get install -y  golang-go
      - go test -v
    when:
      branch:
        - zfs-08